use crate::{run_wat_in_zkvm, waeli};
use risc0_zkvm::Receipt;
use std::error::Error;

/// Represents an element in the execution trace with zkVM verification
#[derive(Debug)]
pub struct ZkTraceElement {
    /// The value generated by the previous waeli call (None for the first iteration)
    pub previous_waeli_output: Option<i32>,
    /// The input to the waeli function (if execution halted) or 0 (if execution completed)
    pub waeli_input: i32,
    /// The final result (if execution completed) or None (if execution halted)
    pub result: Option<i32>,
    /// The zkVM receipt (if execution completed) or None (if execution halted)
    pub receipt: Option<Receipt>,
}

/// Runs the WebAssembly module until completion by dynamically generating values
/// for the 'waeli' host function as needed, with zkVM verification at each step.
///
/// This function:
/// 1. Runs the WAT code in the zkVM until it halts at a host function call
/// 2. Generates a random value using the real host function
/// 3. Resumes the zkVM execution with the generated value
/// 4. Repeats until execution completes normally
/// 5. Collects a trace of the execution with zkVM receipts
///
/// # Arguments
///
/// * `wat` - The WebAssembly Text format content as a string
/// * `initial_value` - The initial value to pass to the 'handle' function
///
/// # Returns
///
/// A tuple containing:
/// - The final result of the WebAssembly module execution
/// - A trace of the execution, with each element containing the previous waeli output,
///   the waeli input, the result, and the zkVM receipt
pub fn run_with_zk_verification(
    wat: &str, 
    initial_value: i32
) -> Result<(i32, Vec<ZkTraceElement>), Box<dyn Error>> {
    let mut host_function_results = Vec::new();
    let mut iteration = 0;
    let mut trace = Vec::new();
    let mut previous_waeli_output: Option<i32> = None;
    
    loop {
        iteration += 1;
        println!("\nIteration #{}", iteration);
        
        // Run the module in the zkVM
        println!("Starting zkVM execution for iteration #{}...", iteration);
        let (result, waeli_input, receipt) = run_wat_in_zkvm(wat, initial_value, &host_function_results)?;
        
        // Add to the trace
        trace.push(ZkTraceElement {
            previous_waeli_output,
            waeli_input,
            result,
            receipt: receipt.clone(),
        });
        
        if let Some(res) = result {
            // Execution completed
            println!("Execution completed with result: {}", res);
            return Ok((res, trace));
        } else {
            // Execution halted due to host function call
            println!("Execution halted with waeli_input: {}", waeli_input);
            
            // Generate a random value using the waeli function
            let random_value = waeli(waeli_input);
            println!("Generated random value: {} (in range [0, {}])", random_value, waeli_input);
            
            // Store this random value for the trace
            previous_waeli_output = Some(random_value);
            
            // Add the result to our list for the next iteration
            host_function_results.push(random_value);
        }
    }
}

/// Example of how to use the run_with_zk_verification function
pub fn example_usage() -> Result<(), Box<dyn Error>> {
    // Parse command line arguments
    let args: Vec<String> = std::env::args().collect();
    
    // Check if we should skip proof generation
    let skip_proof = args.iter().any(|arg| arg == "--fast" || arg == "-f");
    if skip_proof {
        println!("Running in fast mode (skipping proof generation)");
    }
    
    // Load the WebAssembly module from the WAT file
    println!("Loading WebAssembly module...");
    let wat = std::fs::read_to_string("../example3/module.wat")?;
    
    // Run the module with zkVM verification
    println!("Running module with zkVM verification...");
    let (result, trace) = run_with_zk_verification(&wat, 10)?;
    
    // Display the final result
    println!("\nFinal result = {}", result);
    
    // Display the trace
    println!("\nExecution trace with zkVM verification:");
    for (i, element) in trace.iter().enumerate() {
        let prev_output = match element.previous_waeli_output {
            Some(val) => val.to_string(),
            None => "None".to_string(),
        };
        
        let result_str = match element.result {
            Some(val) => format!("Completed with result: {}", val),
            None => format!("Halted at waeli({})", element.waeli_input),
        };
        
        let receipt_info = match &element.receipt {
            Some(receipt) => format!(
                "Receipt: journal size={} bytes, verified successfully", 
                receipt.journal.bytes.len()
            ),
            None => "No receipt (execution halted)".to_string(),
        };
        
        println!("Trace[{}]:", i);
        println!("  Previous waeli output: {}", prev_output);
        println!("  Execution status: {}", result_str);
        println!("  {}", receipt_info);
    }
    
    Ok(())
}
